-- 100 varietales más comercializadas del mundo
-- Ejecutar después de crear las tablas con esquemaDb.sql

INSERT INTO varietals (nombre, descripcion, origen, tipo) VALUES
-- TINTAS (60)
('Cabernet Sauvignon', 'La uva tinta más plantada del mundo, vinos estructurados y longevos', 'Francia (Burdeos)', 'tinta'),
('Merlot', 'Suave y afrutada, componente clave de Burdeos', 'Francia (Burdeos)', 'tinta'),
('Pinot Noir', 'Elegante y compleja, sensible al terroir', 'Francia (Borgoña)', 'tinta'),
('Syrah', 'Potente y especiada, también conocida como Shiraz', 'Francia (Ródano)', 'tinta'),
('Malbec', 'Intensa y oscura, estrella de Argentina', 'Francia (Cahors)', 'tinta'),
('Tempranillo', 'La uva reina de España, base de Rioja y Ribera', 'España', 'tinta'),
('Sangiovese', 'Acidez vibrante, alma de Chianti y Brunello', 'Italia (Toscana)', 'tinta'),
('Grenache', 'Garnacha en español, vinos cálidos y generosos', 'España', 'tinta'),
('Carmenere', 'Redescubierta en Chile, notas herbáceas y especiadas', 'Francia (Burdeos)', 'tinta'),
('Zinfandel', 'Potente y frutal, emblemática de California', 'Croacia/Italia', 'tinta'),
('Barbera', 'Alta acidez, taninos suaves, popular en Piamonte', 'Italia (Piamonte)', 'tinta'),
('Nebbiolo', 'Taninos firmes, aromas de rosa y alquitrán, base de Barolo', 'Italia (Piamonte)', 'tinta'),
('Cabernet Franc', 'Padre de Cabernet Sauvignon, herbal y elegante', 'Francia (País Vasco)', 'tinta'),
('Gamay', 'Ligera y frutal, uva del Beaujolais', 'Francia (Beaujolais)', 'tinta'),
('Mourvedre', 'Monastrell en España, vinos robustos y carnosos', 'España', 'tinta'),
('Petit Verdot', 'Tardía y concentrada, usada en cortes de Burdeos', 'Francia (Burdeos)', 'tinta'),
('Pinotage', 'Cruce sudafricano entre Pinot Noir y Cinsault', 'Sudáfrica', 'tinta'),
('Touriga Nacional', 'La uva noble de Portugal, base del Oporto', 'Portugal', 'tinta'),
('Tannat', 'Taninos potentes, emblemática de Uruguay', 'Francia (Madiran)', 'tinta'),
('Montepulciano', 'Vinos oscuros y accesibles del centro de Italia', 'Italia (Abruzzo)', 'tinta'),
('Dolcetto', 'Suave y afrutado, para consumo temprano', 'Italia (Piamonte)', 'tinta'),
('Corvina', 'Base de Valpolicella y Amarone', 'Italia (Veneto)', 'tinta'),
('Nero dAvola', 'La uva tinta más importante de Sicilia', 'Italia (Sicilia)', 'tinta'),
('Primitivo', 'Idéntica a Zinfandel, vinos potentes de Puglia', 'Italia (Puglia)', 'tinta'),
('Aglianico', 'Estructurada y longeva, el Barolo del sur', 'Italia (Campania)', 'tinta'),
('Cinsault', 'Ligera y aromática, usada en rosados y cortes', 'Francia', 'tinta'),
('Carignan', 'Carinena en España, rústica y productiva', 'España', 'tinta'),
('Graciano', 'Aromática y ácida, complementa al Tempranillo', 'España', 'tinta'),
('Mazuelo', 'Sinónimo de Carignan en Rioja', 'España', 'tinta'),
('Mencia', 'Elegante y mineral, joya del Bierzo', 'España', 'tinta'),
('Bobal', 'Autóctona de Utiel-Requena, color intenso', 'España', 'tinta'),
('Tinta Roriz', 'Sinónimo portugués de Tempranillo', 'Portugal', 'tinta'),
('Touriga Franca', 'Segunda uva noble del Duero portugués', 'Portugal', 'tinta'),
('Tinta Barroca', 'Usada en Oporto y vinos del Duero', 'Portugal', 'tinta'),
('Baga', 'Tanínica y ácida, uva de Bairrada', 'Portugal', 'tinta'),
('Alicante Bouschet', 'Uva tintorera, pulpa coloreada', 'Francia', 'tinta'),
('Petite Sirah', 'Durif en origen, vinos oscuros y tánicos', 'Francia', 'tinta'),
('Shiraz', 'Sinónimo de Syrah en Australia', 'Australia', 'tinta'),
('Bonarda', 'Segunda uva tinta de Argentina tras Malbec', 'Italia/Saboya', 'tinta'),
('Criolla Grande', 'Uva criolla argentina, vinos ligeros', 'Argentina', 'tinta'),
('Cereza', 'Uva criolla de Mendoza, vinos rosados', 'Argentina', 'tinta'),
('Pais', 'Mision en California, uva histórica de Chile', 'España', 'tinta'),
('Listan Negro', 'Uva volcánica de Canarias', 'España (Canarias)', 'tinta'),
('Xinomavro', 'La Nebbiolo griega, vinos longevos de Naoussa', 'Grecia', 'tinta'),
('Agiorgitiko', 'Suave y especiada, uva de Nemea', 'Grecia', 'tinta'),
('Saperavi', 'Uva georgiana de pulpa coloreada', 'Georgia', 'tinta'),
('Blaufrankisch', 'Elegante y picante, uva austriaca', 'Austria', 'tinta'),
('Zweigelt', 'Cruce austriaco, vinos frescos y frutales', 'Austria', 'tinta'),
('St. Laurent', 'Similar a Pinot Noir, uva centroeuropea', 'Austria', 'tinta'),
('Rondo', 'Híbrido resistente, vinos del norte de Europa', 'República Checa', 'tinta'),
('Regent', 'Híbrido alemán resistente a enfermedades', 'Alemania', 'tinta'),
('Dornfelder', 'La tinta más plantada de Alemania', 'Alemania', 'tinta'),
('Pinot Meunier', 'Componente del Champagne, frutal y accesible', 'Francia (Champagne)', 'tinta'),
('Croatina', 'Usada en Oltrepo Pavese y Bonarda', 'Italia (Lombardía)', 'tinta'),
('Lambrusco', 'Uva de vinos espumosos rojos italianos', 'Italia (Emilia)', 'tinta'),
('Freisa', 'Pariente de Nebbiolo, vinos ligeros del Piamonte', 'Italia (Piamonte)', 'tinta'),
('Grignolino', 'Taninos marcados, color claro, Piamonte', 'Italia (Piamonte)', 'tinta'),
('Pallagrello Nero', 'Uva campana redescubierta', 'Italia (Campania)', 'tinta'),
('Gaglioppo', 'La uva tinta de Cirò, Calabria', 'Italia (Calabria)', 'tinta'),
('Frappato', 'Ligera y floral, componente del Cerasuolo', 'Italia (Sicilia)', 'tinta'),

-- BLANCAS (35)
('Chardonnay', 'La blanca más universal, versátil y expresiva', 'Francia (Borgoña)', 'blanca'),
('Sauvignon Blanc', 'Fresca y herbácea, Marlborough y Loira', 'Francia (Loira)', 'blanca'),
('Riesling', 'Aromática y longeva, reina de Alemania y Alsacia', 'Alemania (Ren)', 'blanca'),
('Pinot Grigio', 'Ligera y fresca, estilo italiano', 'Italia (Veneto)', 'blanca'),
('Gewurztraminer', 'Exótica y aromática, lychee y rosas', 'Italia/Alsacia', 'blanca'),
('Chenin Blanc', 'Steen en Sudáfrica, versátil y ácida', 'Francia (Loira)', 'blanca'),
('Viognier', 'Aromática y untuosa, notas de albaricoque', 'Francia (Ródano)', 'blanca'),
('Semillon', 'Base de Sauternes, también en Hunter Valley', 'Francia (Burdeos)', 'blanca'),
('Albariño', 'Fresca y salina, estrella de Rías Baixas', 'España (Galicia)', 'blanca'),
('Verdejo', 'Aromática y herbácea, uva de Rueda', 'España', 'blanca'),
('Torrontes', 'Aromática y floral, uva blanca de Argentina', 'Argentina', 'blanca'),
('Muscat', 'Moscatel, aromas intensos a uva fresca', 'Grecia', 'blanca'),
('Trebbiano', 'Uva blanca más plantada de Italia', 'Italia', 'blanca'),
('Garganega', 'Base de Soave, frescura y mineralidad', 'Italia (Veneto)', 'blanca'),
('Fiano', 'Estructurada y aromática, Campania', 'Italia (Campania)', 'blanca'),
('Greco', 'Mineral y sápida, Greco di Tufo', 'Italia (Campania)', 'blanca'),
('Glera', 'Uva del Prosecco, ligera y espumosa', 'Italia (Veneto)', 'blanca'),
('Vermentino', 'Fresca y salina, Liguria y Cerdeña', 'Italia', 'blanca'),
('Catarratto', 'Uva siciliana de gran producción', 'Italia (Sicilia)', 'blanca'),
('Inzolia', 'Ansonica en Cerdeña, fresca y floral', 'Italia (Sicilia)', 'blanca'),
('Cortese', 'Base de Gavi, elegante y mineral', 'Italia (Piamonte)', 'blanca'),
('Arneis', 'La blanca de Roero, floral y almendrada', 'Italia (Piamonte)', 'blanca'),
('Falanghina', 'Fresca y volcánica, Campania', 'Italia (Campania)', 'blanca'),
('Pecorino', 'Redescubierta en Abruzzo, ácida y aromática', 'Italia (Abruzzo)', 'blanca'),
('Parellada', 'Componente del Cava, fresca y delicada', 'España (Cataluña)', 'blanca'),
('Macabeo', 'Viura en Rioja, base de vinos blancos y Cava', 'España', 'blanca'),
('Xarel·lo', 'Estructural en el Cava, cuerpo y acidez', 'España (Cataluña)', 'blanca'),
('Godello', 'Elegante y mineral, joya de Valdeorras', 'España (Galicia)', 'blanca'),
('Loureira', 'Aromática y floral, componente del Albariño', 'España (Galicia)', 'blanca'),
('Arinto', 'Pedernã en Portugal, ácida y longeva', 'Portugal', 'blanca'),
('Encruzado', 'La blanca noble del Dão', 'Portugal', 'blanca'),
('Antao Vaz', 'Estructurada y tropical, Alentejo', 'Portugal', 'blanca'),
('Fernao Pires', 'Maria Gomes, aromática y floral', 'Portugal', 'blanca'),
('Assyrtiko', 'Mineral y volcánica, reina de Santorini', 'Grecia', 'blanca'),
('Moschofilero', 'Aromática y rosada, uva de Mantinia', 'Grecia', 'blanca'),

-- ROSADAS (5)
('Pinot Gris', 'Versión más coloreada del Pinot, vinos gris-rosado', 'Francia (Alsacia)', 'rosada'),
('Cinsaut Rose', 'Expresión rosada de Cinsaut', 'Francia', 'rosada'),
('Grenache Gris', 'Mutación de Garnacha, vinos rosados', 'España', 'rosada'),
('Tinta Pinheira', 'Uva brasileña para rosados', 'Brasil', 'rosada'),
('Isabel', 'Uva americana, vinos rosados y jugo', 'EE.UU.', 'rosada');
